env:
  browser: true
extends: 'eslint:recommended'
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
  eqeqeq:
    - error
    - always
  camelcase:
    - error
  no-trailing-spaces:
    - error
  curly:
    - error
globals:
  $: false
  __CDN_PATH: false
  __FB_ID: false
  afterEach: false
  angular: false
  beforeEach: false
  cdn: false
  describe: false
  executeTrackingCode: false
  expect: false
  ga: false
  hj: false
  inject: false
  it: false
  jasmine: false
  marked: false
  module: false
  require: false
  spyOn: false
  VD: false

# previous jshint rules. can be deleted in 6 months from now (today is july's 21 of 2017)
#{
#  "globalstrict": true,
#  "eqeqeq": true,
#  "camelcase": false,
#  "trailing": true,
#  "sub": true,
#  "globals": {
#    "angular": false,
#    "describe": false,
#    "it": false,
#    "expect": false,
#    "beforeEach": false,
#    "afterEach": false,
#    "module": false,
#    "inject": false,
#    "VD":false,
#    "cdn":false,
#    "event":false,
#    "alert":false,
#    "window":false,
#    "$":false,
#    "__isMobile": false,
#    "document": false,
#    "twttr": false,
#    "FB": false,
#    "jQuery": false,
#    "CryptoJS": false,
#    "ga": false,
#    "navigator": false,
#    "localytics": false,
#    "__CDN_PATH": false,
#    "Bugsnag":false,
#    "__FB_ID":false,
#    "setTimeout":false,
#    "screen":false,
#    "element":false,
#    "confirm":false,
#    "url":false,
#    "locationDecorator":false,
#    "btoa":false,
#    "KeyboardEvent": false,
#    "MouseEvent": false,
#    "require": false,
#    "process": false,
#    "LocalyticsSession": false,
#    "validthis": false,
#    "executeTrackingCode" : false
#  }
#}
#
#// Objetivo chegar nisso!
#//
#// http://stackoverflow.com/questions/13272532/pragmatic-and-widely-agreed-settings-for-jshint
#//
#// {
#//     "curly": true,
#//     "eqeqeq": true,
#//     "eqnull": true,
#//     "expr": true,
#//     "latedef": true,
#//     "onevar": true,
#//     "noarg": true,
#//     "node": true,
#//     "trailing": true,
#//     "undef": true,
#//     "unused": true
#// }
